// generated by Google Bard
export default function calculateAge(birthday: Date) {
  // Create a Date object for the birthday.
  const birthdayObj = new Date(birthday);

  // Get the current date.
  const today = new Date();

  // Calculate the difference in milliseconds between the two dates.
  const differenceInMilliseconds = today.getTime() - birthdayObj.getTime();

  // Convert the difference in milliseconds to years.
  const years = differenceInMilliseconds / (1000 * 60 * 60 * 24 * 365.25);

  // Round the years to two decimals.
  const roundedYears = Math.round(years * 100) / 100;

  // Return the rounded years.
  return roundedYears;
}
